import { db } from "./index";
import { sources, users, userPreferences, categories } from "./schema";
import { eq } from "drizzle-orm";

const defaultCategories = [
  { slug: "tech", name: "Tech", ingestCron: "0 */4 * * *", curateCron: "0 7,13,19 * * *" },
  { slug: "sports", name: "Sports", ingestCron: "15 */6 * * *", curateCron: "0 6 * * *" },
  { slug: "entertainment", name: "Entertainment", ingestCron: "30 */12 * * *", curateCron: "0 6 * * *" },
];

const defaultSources = [
  // ── Hacker News ──────────────────────────────────────────────
  {
    slug: "hackernews",
    name: "Hacker News",
    type: "hackernews",
    url: "https://news.ycombinator.com",
    config: "{}",
    isDefault: 1,
    vetted: 1,
    description: "Top stories from YCombinator's Hacker News",
  },

  // ── Reddit ───────────────────────────────────────────────────
  {
    slug: "reddit/r/programming",
    name: "r/programming",
    type: "reddit",
    url: "https://reddit.com/r/programming",
    config: JSON.stringify({ subreddit: "programming" }),
    isDefault: 1,
    vetted: 1,
    description: "Programming news and discussion",
  },
  {
    slug: "reddit/r/typescript",
    name: "r/typescript",
    type: "reddit",
    url: "https://reddit.com/r/typescript",
    config: JSON.stringify({ subreddit: "typescript" }),
    isDefault: 1,
    vetted: 1,
    description: "TypeScript community",
  },
  {
    slug: "reddit/r/webdev",
    name: "r/webdev",
    type: "reddit",
    url: "https://reddit.com/r/webdev",
    config: JSON.stringify({ subreddit: "webdev" }),
    isDefault: 1,
    vetted: 1,
    description: "Web development community",
  },
  {
    slug: "reddit/r/machinelearning",
    name: "r/MachineLearning",
    type: "reddit",
    url: "https://reddit.com/r/MachineLearning",
    config: JSON.stringify({ subreddit: "MachineLearning" }),
    isDefault: 1,
    vetted: 1,
    description: "Machine learning research and discussion",
  },
  {
    slug: "reddit/r/devops",
    name: "r/devops",
    type: "reddit",
    url: "https://reddit.com/r/devops",
    config: JSON.stringify({ subreddit: "devops" }),
    isDefault: 1,
    vetted: 1,
    description: "DevOps practices and tooling",
  },
  {
    slug: "reddit/r/kubernetes",
    name: "r/kubernetes",
    type: "reddit",
    url: "https://reddit.com/r/kubernetes",
    config: JSON.stringify({ subreddit: "kubernetes" }),
    isDefault: 1,
    vetted: 1,
    description: "Kubernetes community",
  },

  // ── RSS: Cloud Providers ─────────────────────────────────────
  {
    slug: "rss/aws-blog",
    name: "AWS Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/aws/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/aws/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Primary AWS blog — new services, features, announcements",
  },
  {
    slug: "rss/aws-whats-new",
    name: "AWS What's New",
    type: "rss",
    url: "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/about-aws/whats-new/recent/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Every AWS service update and new feature launch (high volume)",
  },
  {
    slug: "rss/aws-security",
    name: "AWS Security Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/security/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/security/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "AWS security best practices, compliance, and encryption",
  },
  {
    slug: "rss/aws-architecture",
    name: "AWS Architecture Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/architecture/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/architecture/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Reference architectures and Well-Architected guidance",
  },
  {
    slug: "rss/aws-containers",
    name: "AWS Containers Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/containers/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/containers/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "ECS, EKS, Fargate, and container ecosystem on AWS",
  },
  {
    slug: "rss/gcp-blog",
    name: "Google Cloud Blog",
    type: "rss",
    url: "https://cloudblog.withgoogle.com/rss/",
    config: JSON.stringify({ feedUrl: "https://cloudblog.withgoogle.com/rss/" }),
    isDefault: 1,
    vetted: 1,
    description: "Google Cloud product announcements and case studies",
  },
  {
    slug: "rss/azure-blog",
    name: "Azure Blog",
    type: "rss",
    url: "https://azure.microsoft.com/en-us/blog/feed/",
    config: JSON.stringify({ feedUrl: "https://azure.microsoft.com/en-us/blog/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Azure announcements, tutorials, and updates",
  },
  {
    slug: "rss/cloudflare",
    name: "Cloudflare Blog",
    type: "rss",
    url: "https://blog.cloudflare.com/rss/",
    config: JSON.stringify({ feedUrl: "https://blog.cloudflare.com/rss/" }),
    isDefault: 1,
    vetted: 1,
    description: "Product launches, engineering deep dives, internet security",
  },
  {
    slug: "rss/vercel",
    name: "Vercel Blog",
    type: "rss",
    url: "https://vercel.com/atom",
    config: JSON.stringify({ feedUrl: "https://vercel.com/atom" }),
    isDefault: 1,
    vetted: 1,
    description: "Next.js hosting, edge functions, frontend cloud",
  },
  {
    slug: "rss/hashicorp",
    name: "HashiCorp Blog",
    type: "rss",
    url: "https://www.hashicorp.com/blog/feed.xml",
    config: JSON.stringify({ feedUrl: "https://www.hashicorp.com/blog/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Terraform, Vault, Consul, Nomad, and infrastructure automation",
  },

  // ── RSS: Security ────────────────────────────────────────────
  {
    slug: "rss/krebs",
    name: "Krebs on Security",
    type: "rss",
    url: "https://krebsonsecurity.com/feed/",
    config: JSON.stringify({ feedUrl: "https://krebsonsecurity.com/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Investigative journalism on cybercrime and security",
  },
  {
    slug: "rss/hacker-news-security",
    name: "The Hacker News",
    type: "rss",
    url: "https://feeds.feedburner.com/TheHackersNews",
    config: JSON.stringify({ feedUrl: "https://feeds.feedburner.com/TheHackersNews" }),
    isDefault: 1,
    vetted: 1,
    description: "Cybersecurity news — vulnerabilities, breaches, threats",
  },
  {
    slug: "rss/bleeping-computer",
    name: "BleepingComputer",
    type: "rss",
    url: "https://www.bleepingcomputer.com/feed/",
    config: JSON.stringify({ feedUrl: "https://www.bleepingcomputer.com/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Breaking security news and malware analysis",
  },
  {
    slug: "rss/schneier",
    name: "Schneier on Security",
    type: "rss",
    url: "https://www.schneier.com/feed/atom/",
    config: JSON.stringify({ feedUrl: "https://www.schneier.com/feed/atom/" }),
    isDefault: 0,
    vetted: 1,
    description: "Expert commentary on security, privacy, and cryptography",
  },
  {
    slug: "rss/project-zero",
    name: "Google Project Zero",
    type: "rss",
    url: "https://googleprojectzero.blogspot.com/feeds/posts/default",
    config: JSON.stringify({ feedUrl: "https://googleprojectzero.blogspot.com/feeds/posts/default" }),
    isDefault: 0,
    vetted: 1,
    description: "Vulnerability research and zero-day disclosure",
  },
  {
    slug: "rss/portswigger",
    name: "PortSwigger Research",
    type: "rss",
    url: "https://portswigger.net/research/rss",
    config: JSON.stringify({ feedUrl: "https://portswigger.net/research/rss" }),
    isDefault: 0,
    vetted: 1,
    description: "Web security research from the creators of Burp Suite",
  },

  // ── RSS: AI & Research ───────────────────────────────────────
  {
    slug: "rss/openai",
    name: "OpenAI Blog",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    config: JSON.stringify({ feedUrl: "https://openai.com/blog/rss.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Model releases, research papers, and safety updates",
  },
  {
    slug: "rss/deepmind",
    name: "Google DeepMind",
    type: "rss",
    url: "https://deepmind.google/blog/rss.xml",
    config: JSON.stringify({ feedUrl: "https://deepmind.google/blog/rss.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "AI research breakthroughs and scientific applications",
  },
  {
    slug: "rss/huggingface",
    name: "Hugging Face Blog",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    config: JSON.stringify({ feedUrl: "https://huggingface.co/blog/feed.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Open-source ML models, transformers, and community updates",
  },
  {
    slug: "rss/simon-willison",
    name: "Simon Willison's Blog",
    type: "rss",
    url: "https://simonwillison.net/atom/everything/",
    config: JSON.stringify({ feedUrl: "https://simonwillison.net/atom/everything/" }),
    isDefault: 1,
    vetted: 1,
    description: "Prolific coverage of LLMs, AI tools, Python, and open data",
  },
  {
    slug: "rss/lilian-weng",
    name: "Lilian Weng",
    type: "rss",
    url: "https://lilianweng.github.io/index.xml",
    config: JSON.stringify({ feedUrl: "https://lilianweng.github.io/index.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Exceptional long-form ML explainers from OpenAI researcher",
  },

  // ── RSS: General Tech News ───────────────────────────────────
  {
    slug: "rss/tldr",
    name: "TLDR Newsletter",
    type: "rss",
    url: "https://tldr.tech/api/rss/tech",
    config: JSON.stringify({ feedUrl: "https://tldr.tech/api/rss/tech" }),
    isDefault: 1,
    vetted: 1,
    description: "Daily tech newsletter digest",
  },
  {
    slug: "rss/ars-technica",
    name: "Ars Technica",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    config: JSON.stringify({ feedUrl: "https://feeds.arstechnica.com/arstechnica/index" }),
    isDefault: 1,
    vetted: 1,
    description: "In-depth tech, science, and policy journalism",
  },
  {
    slug: "rss/the-verge",
    name: "The Verge",
    type: "rss",
    url: "https://www.theverge.com/rss/index.xml",
    config: JSON.stringify({ feedUrl: "https://www.theverge.com/rss/index.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Tech, science, culture, and industry news",
  },
  {
    slug: "rss/techcrunch",
    name: "TechCrunch",
    type: "rss",
    url: "https://techcrunch.com/feed/",
    config: JSON.stringify({ feedUrl: "https://techcrunch.com/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Startup ecosystem, funding rounds, and tech industry",
  },
  {
    slug: "rss/techmeme",
    name: "Techmeme",
    type: "rss",
    url: "https://www.techmeme.com/feed.xml",
    config: JSON.stringify({ feedUrl: "https://www.techmeme.com/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Curated aggregation of the most important tech news",
  },
  {
    slug: "rss/lobsters",
    name: "Lobsters",
    type: "rss",
    url: "https://lobste.rs/rss",
    config: JSON.stringify({ feedUrl: "https://lobste.rs/rss" }),
    isDefault: 1,
    vetted: 1,
    description: "Invite-only computing-focused link aggregation",
  },
  {
    slug: "rss/pragmatic-engineer",
    name: "The Pragmatic Engineer",
    type: "rss",
    url: "https://blog.pragmaticengineer.com/rss/",
    config: JSON.stringify({ feedUrl: "https://blog.pragmaticengineer.com/rss/" }),
    isDefault: 0,
    vetted: 1,
    description: "Engineering management and big tech insights",
  },
  {
    slug: "rss/netflix-tech",
    name: "Netflix Tech Blog",
    type: "rss",
    url: "https://medium.com/feed/netflix-techblog",
    config: JSON.stringify({ feedUrl: "https://medium.com/feed/netflix-techblog" }),
    isDefault: 0,
    vetted: 1,
    description: "Distributed systems, streaming infrastructure, and ML at scale",
  },

  // ── RSS: Developer Tools & Frameworks ────────────────────────
  {
    slug: "rss/react",
    name: "React Blog",
    type: "rss",
    url: "https://react.dev/rss.xml",
    config: JSON.stringify({ feedUrl: "https://react.dev/rss.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Official React team updates and releases",
  },
  {
    slug: "rss/typescript",
    name: "TypeScript Blog",
    type: "rss",
    url: "https://devblogs.microsoft.com/typescript/feed/",
    config: JSON.stringify({ feedUrl: "https://devblogs.microsoft.com/typescript/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "TypeScript releases and type system features",
  },
  {
    slug: "rss/tailwind",
    name: "Tailwind CSS Blog",
    type: "rss",
    url: "https://tailwindcss.com/feeds/feed.xml",
    config: JSON.stringify({ feedUrl: "https://tailwindcss.com/feeds/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Tailwind releases and utility-first CSS updates",
  },
  {
    slug: "rss/rust",
    name: "Rust Blog",
    type: "rss",
    url: "https://blog.rust-lang.org/feed.xml",
    config: JSON.stringify({ feedUrl: "https://blog.rust-lang.org/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Rust releases, edition updates, and RFCs",
  },
  {
    slug: "rss/go",
    name: "Go Blog",
    type: "rss",
    url: "https://go.dev/blog/feed.atom",
    config: JSON.stringify({ feedUrl: "https://go.dev/blog/feed.atom" }),
    isDefault: 0,
    vetted: 1,
    description: "Official Go blog — releases, proposals, patterns",
  },
  {
    slug: "rss/github-blog",
    name: "GitHub Blog",
    type: "rss",
    url: "https://github.blog/feed/",
    config: JSON.stringify({ feedUrl: "https://github.blog/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "GitHub features, Copilot updates, developer ecosystem",
  },
  {
    slug: "rss/github-changelog",
    name: "GitHub Changelog",
    type: "rss",
    url: "https://github.blog/changelog/feed/",
    config: JSON.stringify({ feedUrl: "https://github.blog/changelog/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Granular changelog of every GitHub feature and UI change",
  },
  {
    slug: "rss/kubernetes",
    name: "Kubernetes Blog",
    type: "rss",
    url: "https://kubernetes.io/feed.xml",
    config: JSON.stringify({ feedUrl: "https://kubernetes.io/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "K8s releases, KEPs, and CNCF ecosystem updates",
  },
  {
    slug: "rss/docker",
    name: "Docker Blog",
    type: "rss",
    url: "https://www.docker.com/blog/feed/",
    config: JSON.stringify({ feedUrl: "https://www.docker.com/blog/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Docker Desktop, Docker Hub, and container ecosystem",
  },
  {
    slug: "rss/grafana",
    name: "Grafana Blog",
    type: "rss",
    url: "https://grafana.com/blog/index.xml",
    config: JSON.stringify({ feedUrl: "https://grafana.com/blog/index.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Observability, dashboards, Loki, Tempo, and Mimir",
  },

  // ── YouTube ──────────────────────────────────────────────────
  {
    slug: "youtube/fireship",
    name: "Fireship",
    type: "youtube",
    url: "https://www.youtube.com/@Fireship",
    config: JSON.stringify({ channelId: "UCsBjURrPoezykLs9EqgamOA" }),
    isDefault: 0,
    vetted: 1,
    description: "Fast-paced tech tutorials and news",
  },
  {
    slug: "youtube/theo",
    name: "Theo - t3.gg",
    type: "youtube",
    url: "https://www.youtube.com/@t3dotgg",
    config: JSON.stringify({ channelId: "UCbRP3c757lWg9M-U7TyEkXA" }),
    isDefault: 0,
    vetted: 1,
    description: "TypeScript, Next.js, tRPC, and web dev opinions",
  },
  {
    slug: "youtube/3blue1brown",
    name: "3Blue1Brown",
    type: "youtube",
    url: "https://www.youtube.com/@3blue1brown",
    config: JSON.stringify({ channelId: "UCYO_jab_esuFRV4b17AJtAw" }),
    isDefault: 0,
    vetted: 1,
    description: "Mathematical foundations of ML/AI with visual explanations",
  },
  {
    slug: "youtube/andrej-karpathy",
    name: "Andrej Karpathy",
    type: "youtube",
    url: "https://www.youtube.com/@andrejkarpathy",
    config: JSON.stringify({ channelId: "UCXUPKJO5MZQN11PqgIvyuvQ" }),
    isDefault: 0,
    vetted: 1,
    description: "First-principles neural network and LLM tutorials",
  },
  {
    slug: "youtube/yannic-kilcher",
    name: "Yannic Kilcher",
    type: "youtube",
    url: "https://www.youtube.com/@YannicKilcher",
    config: JSON.stringify({ channelId: "UCZHmQk67mSJgfCCTn7xBfew" }),
    isDefault: 0,
    vetted: 1,
    description: "Rigorous ML research paper breakdowns",
  },
  {
    slug: "youtube/two-minute-papers",
    name: "Two Minute Papers",
    type: "youtube",
    url: "https://www.youtube.com/@TwoMinutePapers",
    config: JSON.stringify({ channelId: "UCbfYPyITQ-7l4upoX8nvctg" }),
    isDefault: 1,
    vetted: 1,
    description: "Concise summaries of cutting-edge AI research",
  },
  {
    slug: "youtube/ai-explained",
    name: "AI Explained",
    type: "youtube",
    url: "https://www.youtube.com/@aiexplained-official",
    config: JSON.stringify({ channelId: "UCNJ1Ymd5yFuUPtn21xtRbbw" }),
    isDefault: 1,
    vetted: 1,
    description: "Thorough, measured analysis of major AI developments",
  },
  {
    slug: "youtube/1littlecoder",
    name: "1littlecoder",
    type: "youtube",
    url: "https://www.youtube.com/@1littlecoder",
    config: JSON.stringify({ channelId: "UCpV_X0VrL8-jg3t6wYGS-1g" }),
    isDefault: 1,
    vetted: 1,
    description: "AI/ML coding tutorials and tool walkthroughs",
  },
  {
    slug: "youtube/dylan-curious",
    name: "Dylan Curious",
    type: "youtube",
    url: "https://www.youtube.com/@Dylan_Curious",
    config: JSON.stringify({ channelId: "UCpdyFxSktWo3W6kMYfmk6lg" }),
    isDefault: 1,
    vetted: 1,
    description: "AI and tech curiosity-driven explainers",
  },
  {
    slug: "youtube/arseny-shatokhin",
    name: "Arseny Shatokhin",
    type: "youtube",
    url: "https://www.youtube.com/@vrsen",
    config: JSON.stringify({ channelId: "UCSv4qL8vmoSH7GaPjuqRiCQ" }),
    isDefault: 1,
    vetted: 1,
    description: "AI engineering and agent development tutorials",
  },
  {
    slug: "youtube/matt-pocock",
    name: "Matt Pocock",
    type: "youtube",
    url: "https://www.youtube.com/@mattpocockuk",
    config: JSON.stringify({ channelId: "UCswG6FSbgZjbWtdf_hMLaow" }),
    isDefault: 0,
    vetted: 1,
    description: "Advanced TypeScript patterns and type-level programming",
  },
  {
    slug: "youtube/primeagen",
    name: "ThePrimeagen",
    type: "youtube",
    url: "https://www.youtube.com/@ThePrimeagen",
    config: JSON.stringify({ channelId: "UC8ENHE5xdFSwx71u3fDH5Xw" }),
    isDefault: 0,
    vetted: 1,
    description: "Backend performance, Rust, Go, algorithms, engineering culture",
  },
  {
    slug: "youtube/jack-herrington",
    name: "Jack Herrington",
    type: "youtube",
    url: "https://www.youtube.com/@jherr",
    config: JSON.stringify({ channelId: "UC6vRUjYqDuoUsYsku86Lrsw" }),
    isDefault: 0,
    vetted: 1,
    description: "Advanced React patterns and micro-frontends",
  },
  // ── Bluesky ──────────────────────────────────────────────────
  {
    slug: "bluesky/simon-willison",
    name: "Simon Willison",
    type: "bluesky",
    url: "https://bsky.app/profile/simonwillison.net",
    config: JSON.stringify({ actor: "simonwillison.net" }),
    isDefault: 1,
    vetted: 1,
    description: "AI tools, LLMs, Python, and open data",
  },
  {
    slug: "bluesky/swyx",
    name: "swyx",
    type: "bluesky",
    url: "https://bsky.app/profile/swyx.io",
    config: JSON.stringify({ actor: "swyx.io" }),
    isDefault: 1,
    vetted: 1,
    description: "Latent Space podcast, AI engineering",
  },
  {
    slug: "bluesky/andrej-karpathy",
    name: "Andrej Karpathy",
    type: "bluesky",
    url: "https://bsky.app/profile/karpathy.bsky.social",
    config: JSON.stringify({ actor: "karpathy.bsky.social" }),
    isDefault: 1,
    vetted: 1,
    description: "AI researcher, deep learning and LLMs",
  },
  {
    slug: "bluesky/kelsey-hightower",
    name: "Kelsey Hightower",
    type: "bluesky",
    url: "https://bsky.app/profile/kelseyhightower.com",
    config: JSON.stringify({ actor: "kelseyhightower.com" }),
    isDefault: 1,
    vetted: 1,
    description: "Cloud-native, Kubernetes, infrastructure",
  },
  {
    slug: "bluesky/julia-evans",
    name: "Julia Evans",
    type: "bluesky",
    url: "https://bsky.app/profile/b0rk.jvns.ca",
    config: JSON.stringify({ actor: "b0rk.jvns.ca" }),
    isDefault: 1,
    vetted: 1,
    description: "Wizard Zines — Linux, networking, debugging",
  },
  {
    slug: "bluesky/dan-abramov",
    name: "Dan Abramov",
    type: "bluesky",
    url: "https://bsky.app/profile/danabra.mov",
    config: JSON.stringify({ actor: "danabra.mov" }),
    isDefault: 1,
    vetted: 1,
    description: "Former React core team, Redux creator",
  },
  {
    slug: "bluesky/kent-c-dodds",
    name: "Kent C. Dodds",
    type: "bluesky",
    url: "https://bsky.app/profile/kentcdodds.com",
    config: JSON.stringify({ actor: "kentcdodds.com" }),
    isDefault: 0,
    vetted: 1,
    description: "EpicWeb.dev, React and testing expert",
  },
  {
    slug: "bluesky/charity-majors",
    name: "Charity Majors",
    type: "bluesky",
    url: "https://bsky.app/profile/charity.wtf",
    config: JSON.stringify({ actor: "charity.wtf" }),
    isDefault: 0,
    vetted: 1,
    description: "Honeycomb CTO, observability pioneer",
  },
  {
    slug: "bluesky/theo",
    name: "Theo",
    type: "bluesky",
    url: "https://bsky.app/profile/t3.gg",
    config: JSON.stringify({ actor: "t3.gg" }),
    isDefault: 0,
    vetted: 1,
    description: "T3 stack, TypeScript, Next.js",
  },
  {
    slug: "bluesky/rich-harris",
    name: "Rich Harris",
    type: "bluesky",
    url: "https://bsky.app/profile/rich-harris.dev",
    config: JSON.stringify({ actor: "rich-harris.dev" }),
    isDefault: 0,
    vetted: 1,
    description: "Creator of Svelte and SvelteKit",
  },
  {
    slug: "bluesky/matt-pocock",
    name: "Matt Pocock",
    type: "bluesky",
    url: "https://bsky.app/profile/mattpocock.com",
    config: JSON.stringify({ actor: "mattpocock.com" }),
    isDefault: 0,
    vetted: 1,
    description: "Total TypeScript, TS educator",
  },
  {
    slug: "bluesky/corey-quinn",
    name: "Corey Quinn",
    type: "bluesky",
    url: "https://bsky.app/profile/quinnypig.com",
    config: JSON.stringify({ actor: "quinnypig.com" }),
    isDefault: 0,
    vetted: 1,
    description: "Last Week in AWS, cloud economics",
  },
  {
    slug: "bluesky/liz-rice",
    name: "Liz Rice",
    type: "bluesky",
    url: "https://bsky.app/profile/lizrice.com",
    config: JSON.stringify({ actor: "lizrice.com" }),
    isDefault: 0,
    vetted: 1,
    description: "eBPF/Cilium expert, container security author",
  },
  {
    slug: "bluesky/wes-bos",
    name: "Wes Bos",
    type: "bluesky",
    url: "https://bsky.app/profile/wesbos.com",
    config: JSON.stringify({ actor: "wesbos.com" }),
    isDefault: 0,
    vetted: 1,
    description: "Syntax podcast, JS/CSS/Node courses",
  },

  // ── Sports ───────────────────────────────────────────────────
  {
    slug: "rss/espn",
    name: "ESPN",
    type: "rss",
    url: "https://www.espn.com/espn/rss/news",
    config: JSON.stringify({ feedUrl: "https://www.espn.com/espn/rss/news" }),
    isDefault: 1,
    vetted: 1,
    description: "Top US sports headlines",
    category: "sports",
  },
  {
    slug: "reddit/r/sports",
    name: "r/sports",
    type: "reddit",
    url: "https://reddit.com/r/sports",
    config: JSON.stringify({ subreddit: "sports" }),
    isDefault: 1,
    vetted: 1,
    description: "General sports news and discussion",
    category: "sports",
  },
  {
    slug: "reddit/r/nba",
    name: "r/nba",
    type: "reddit",
    url: "https://reddit.com/r/nba",
    config: JSON.stringify({ subreddit: "nba" }),
    isDefault: 0,
    vetted: 1,
    description: "NBA news and discussion",
    category: "sports",
  },
  {
    slug: "reddit/r/soccer",
    name: "r/soccer",
    type: "reddit",
    url: "https://reddit.com/r/soccer",
    config: JSON.stringify({ subreddit: "soccer" }),
    isDefault: 0,
    vetted: 1,
    description: "Global football/soccer news",
    category: "sports",
  },
  {
    slug: "rss/autosport",
    name: "Autosport",
    type: "rss",
    url: "https://www.autosport.com/rss/feed/all",
    config: JSON.stringify({"feedUrl":"https://www.autosport.com/rss/feed/all"}),
    isDefault: 0,
    vetted: 1,
    description: "Comprehensive motorsport news and race coverage",
    category: "sports",
  },
  {
    slug: "rss/bbc-sport-football",
    name: "BBC Sport Football",
    type: "rss",
    url: "https://feeds.bbci.co.uk/sport/football/rss.xml",
    config: JSON.stringify({"feedUrl":"https://feeds.bbci.co.uk/sport/football/rss.xml"}),
    isDefault: 1,
    vetted: 1,
    description: "BBC's authoritative Premier League and international football coverage",
    category: "sports",
  },
  {
    slug: "youtube/brett-kollmann",
    name: "Brett Kollmann",
    type: "youtube",
    url: "https://www.youtube.com/@BrettKollmann",
    config: JSON.stringify({"channelId":"UCYzfVBuCfGz-oF3aOCGgO5g"}),
    isDefault: 0,
    vetted: 1,
    description: "NFL film breakdowns and draft prospect analysis",
    category: "sports",
  },
  {
    slug: "rss/cbs-sports",
    name: "CBS Sports",
    type: "rss",
    url: "https://www.cbssports.com/rss/headlines/",
    config: JSON.stringify({"feedUrl":"https://www.cbssports.com/rss/headlines/"}),
    isDefault: 1,
    vetted: 1,
    description: "CBS Sports top headlines and breaking news",
    category: "sports",
  },
  {
    slug: "youtube/chain-bear",
    name: "Chain Bear",
    type: "youtube",
    url: "https://www.youtube.com/@chainbear",
    config: JSON.stringify({"channelId":"UC7u-Dg0jb7KtZnTPhytab5g"}),
    isDefault: 0,
    vetted: 1,
    description: "F1 rules, strategy, and technical concepts explained",
    category: "sports",
  },
  {
    slug: "youtube/espn",
    name: "ESPN",
    type: "youtube",
    url: "https://www.youtube.com/@espn",
    config: JSON.stringify({"channelId":"UCkifs0jETNrZXQibjc7hPvQ"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN highlights, analysis, and daily sports coverage",
    category: "sports",
  },
  {
    slug: "bluesky/espn",
    name: "ESPN",
    type: "bluesky",
    url: "https://bsky.app/profile/espn.com",
    config: JSON.stringify({"actor":"espn.com"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN breaking news and highlights on Bluesky",
    category: "sports",
  },
  {
    slug: "rss/espn-mlb",
    name: "ESPN MLB",
    type: "rss",
    url: "https://www.espn.com/espn/rss/mlb/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/mlb/news"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN MLB news, trades, and standings",
    category: "sports",
  },
  {
    slug: "rss/espn-motorsport",
    name: "ESPN Motorsport",
    type: "rss",
    url: "https://www.espn.com/espn/rss/rpm/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/rpm/news"}),
    isDefault: 0,
    vetted: 1,
    description: "ESPN racing and motorsport coverage",
    category: "sports",
  },
  {
    slug: "rss/espn-nba",
    name: "ESPN NBA",
    type: "rss",
    url: "https://www.espn.com/espn/rss/nba/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/nba/news"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN NBA news, trades, and game recaps",
    category: "sports",
  },
  {
    slug: "rss/espn-nfl",
    name: "ESPN NFL",
    type: "rss",
    url: "https://www.espn.com/espn/rss/nfl/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/nfl/news"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN NFL news, free agency, and game analysis",
    category: "sports",
  },
  {
    slug: "rss/espn-nhl",
    name: "ESPN NHL",
    type: "rss",
    url: "https://www.espn.com/espn/rss/nhl/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/nhl/news"}),
    isDefault: 0,
    vetted: 1,
    description: "ESPN NHL news, playoffs, and hockey coverage",
    category: "sports",
  },
  {
    slug: "rss/espn-soccer",
    name: "ESPN Soccer",
    type: "rss",
    url: "https://www.espn.com/espn/rss/soccer/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/soccer/news"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN global football/soccer coverage",
    category: "sports",
  },
  {
    slug: "rss/espn-top-news",
    name: "ESPN Top News",
    type: "rss",
    url: "https://www.espn.com/espn/rss/news",
    config: JSON.stringify({"feedUrl":"https://www.espn.com/espn/rss/news"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN top headlines across all sports",
    category: "sports",
  },
  {
    slug: "bluesky/fabrizio-romano",
    name: "Fabrizio Romano",
    type: "bluesky",
    url: "https://bsky.app/profile/fabriziorom.bsky.social",
    config: JSON.stringify({"actor":"fabriziorom.bsky.social"}),
    isDefault: 1,
    vetted: 1,
    description: "The definitive source for soccer transfer news worldwide",
    category: "sports",
  },
  {
    slug: "rss/formula1",
    name: "Formula1.com",
    type: "rss",
    url: "https://www.formula1.com/content/fom-website/en/latest/all.xml",
    config: JSON.stringify({"feedUrl":"https://www.formula1.com/content/fom-website/en/latest/all.xml"}),
    isDefault: 1,
    vetted: 1,
    description: "Official F1 news, results, and race coverage",
    category: "sports",
  },
  {
    slug: "rss/fourfourtwo",
    name: "FourFourTwo",
    type: "rss",
    url: "https://www.fourfourtwo.com/feeds.xml",
    config: JSON.stringify({"feedUrl":"https://www.fourfourtwo.com/feeds.xml"}),
    isDefault: 0,
    vetted: 1,
    description: "Football features, interviews, and analysis",
    category: "sports",
  },
  {
    slug: "rss/golfweek",
    name: "Golfweek",
    type: "rss",
    url: "https://golfweek.usatoday.com/feed/",
    config: JSON.stringify({"feedUrl":"https://golfweek.usatoday.com/feed/"}),
    isDefault: 0,
    vetted: 0,
    description: "PGA Tour news, rankings, and tournament coverage",
    category: "sports",
  },
  {
    slug: "youtube/hitc-sevens",
    name: "HITC Sevens",
    type: "youtube",
    url: "https://www.youtube.com/@HITCSevens",
    config: JSON.stringify({"channelId":"UCb2grEI22GnNsTh-gC8Jz2Q"}),
    isDefault: 0,
    vetted: 1,
    description: "Football history lists and retrospectives",
    category: "sports",
  },
  {
    slug: "bluesky/ian-rapoport",
    name: "Ian Rapoport",
    type: "bluesky",
    url: "https://bsky.app/profile/rapsheet.bsky.social",
    config: JSON.stringify({"actor":"rapsheet.bsky.social"}),
    isDefault: 1,
    vetted: 1,
    description: "NFL Network insider — breaking NFL transaction news",
    category: "sports",
  },
  {
    slug: "bluesky/jeff-passan",
    name: "Jeff Passan",
    type: "bluesky",
    url: "https://bsky.app/profile/jeffpasan.bsky.social",
    config: JSON.stringify({"actor":"jeffpasan.bsky.social"}),
    isDefault: 1,
    vetted: 1,
    description: "ESPN MLB insider — breaking baseball transaction news",
    category: "sports",
  },
  {
    slug: "youtube/jomboy-media",
    name: "JomBoy Media",
    type: "youtube",
    url: "https://www.youtube.com/@JomboyMedia",
    config: JSON.stringify({"channelId":"UCl9E4Zxa8CVr2LBLBPR8jcg"}),
    isDefault: 1,
    vetted: 1,
    description: "Baseball breakdowns and multi-sport lip reading/analysis",
    category: "sports",
  },
  {
    slug: "youtube/josh-revell",
    name: "Josh Revell",
    type: "youtube",
    url: "https://www.youtube.com/@JoshRevell",
    config: JSON.stringify({"channelId":"UCVcbMo3-lXFLMGCx6eltcgw"}),
    isDefault: 0,
    vetted: 1,
    description: "F1 commentary, history, and entertaining race reviews",
    category: "sports",
  },
  {
    slug: "youtube/jxmyhighroller",
    name: "JxmyHighroller",
    type: "youtube",
    url: "https://www.youtube.com/@JxmyHighroller",
    config: JSON.stringify({"channelId":"UCdradO50Pgep5MOQ0RHO4yw"}),
    isDefault: 0,
    vetted: 1,
    description: "NBA data stories and player comparisons",
    category: "sports",
  },
  {
    slug: "bluesky/ken-rosenthal",
    name: "Ken Rosenthal",
    type: "bluesky",
    url: "https://bsky.app/profile/ken-rosenthal.bsky.social",
    config: JSON.stringify({"actor":"ken-rosenthal.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "Senior MLB reporter for The Athletic",
    category: "sports",
  },
  {
    slug: "bluesky/mina-kimes",
    name: "Mina Kimes",
    type: "bluesky",
    url: "https://bsky.app/profile/minakimes.bsky.social",
    config: JSON.stringify({"actor":"minakimes.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "ESPN NFL analyst and general sports commentary",
    category: "sports",
  },
  {
    slug: "rss/mlb-trade-rumors",
    name: "MLB Trade Rumors",
    type: "rss",
    url: "https://www.mlbtraderumors.com/feed",
    config: JSON.stringify({"feedUrl":"https://www.mlbtraderumors.com/feed"}),
    isDefault: 1,
    vetted: 1,
    description: "Breaking MLB free agency, trades, and transaction news",
    category: "sports",
  },
  {
    slug: "rss/mma-fighting",
    name: "MMA Fighting",
    type: "rss",
    url: "https://www.mmafighting.com/rss/current",
    config: JSON.stringify({"feedUrl":"https://www.mmafighting.com/rss/current"}),
    isDefault: 0,
    vetted: 0,
    description: "UFC and MMA news from Vox Media",
    category: "sports",
  },
  {
    slug: "rss/mma-junkie",
    name: "MMA Junkie",
    type: "rss",
    url: "https://mmajunkie.usatoday.com/feed",
    config: JSON.stringify({"feedUrl":"https://mmajunkie.usatoday.com/feed"}),
    isDefault: 0,
    vetted: 0,
    description: "UFC fight news, results, and rankings",
    category: "sports",
  },
  {
    slug: "rss/pff",
    name: "Pro Football Focus",
    type: "rss",
    url: "https://www.pff.com/feed",
    config: JSON.stringify({"feedUrl":"https://www.pff.com/feed"}),
    isDefault: 0,
    vetted: 1,
    description: "Advanced NFL analytics and player grading",
    category: "sports",
  },
  {
    slug: "reddit/r/baseball",
    name: "r/baseball",
    type: "reddit",
    url: "https://reddit.com/r/baseball",
    config: JSON.stringify({"subreddit":"baseball"}),
    isDefault: 1,
    vetted: 1,
    description: "MLB discussion, highlights, and statistics",
    category: "sports",
  },
  {
    slug: "reddit/r/boxing",
    name: "r/boxing",
    type: "reddit",
    url: "https://reddit.com/r/boxing",
    config: JSON.stringify({"subreddit":"boxing"}),
    isDefault: 0,
    vetted: 1,
    description: "Boxing news, fight announcements, and discussion",
    category: "sports",
  },
  {
    slug: "reddit/r/cfb",
    name: "r/CFB",
    type: "reddit",
    url: "https://reddit.com/r/CFB",
    config: JSON.stringify({"subreddit":"CFB"}),
    isDefault: 0,
    vetted: 1,
    description: "College football news and game threads",
    category: "sports",
  },
  {
    slug: "reddit/r/collegebasketball",
    name: "r/CollegeBasketball",
    type: "reddit",
    url: "https://reddit.com/r/CollegeBasketball",
    config: JSON.stringify({"subreddit":"CollegeBasketball"}),
    isDefault: 0,
    vetted: 1,
    description: "NCAA basketball discussion and March Madness",
    category: "sports",
  },
  {
    slug: "reddit/r/fantasyfootball",
    name: "r/FantasyFootball",
    type: "reddit",
    url: "https://reddit.com/r/fantasyfootball",
    config: JSON.stringify({"subreddit":"fantasyfootball"}),
    isDefault: 0,
    vetted: 1,
    description: "Fantasy football strategy and waiver wire advice",
    category: "sports",
  },
  {
    slug: "reddit/r/formula1",
    name: "r/formula1",
    type: "reddit",
    url: "https://reddit.com/r/formula1",
    config: JSON.stringify({"subreddit":"formula1"}),
    isDefault: 0,
    vetted: 1,
    description: "Formula 1 community, race discussion, and memes",
    category: "sports",
  },
  {
    slug: "reddit/r/golf",
    name: "r/golf",
    type: "reddit",
    url: "https://reddit.com/r/golf",
    config: JSON.stringify({"subreddit":"golf"}),
    isDefault: 0,
    vetted: 1,
    description: "Golf community and PGA Tour discussion",
    category: "sports",
  },
  {
    slug: "reddit/r/hockey",
    name: "r/hockey",
    type: "reddit",
    url: "https://reddit.com/r/hockey",
    config: JSON.stringify({"subreddit":"hockey"}),
    isDefault: 0,
    vetted: 1,
    description: "NHL and hockey community",
    category: "sports",
  },
  {
    slug: "reddit/r/mma",
    name: "r/MMA",
    type: "reddit",
    url: "https://reddit.com/r/MMA",
    config: JSON.stringify({"subreddit":"MMA"}),
    isDefault: 0,
    vetted: 1,
    description: "UFC and MMA fight discussion and news",
    category: "sports",
  },
  {
    slug: "reddit/r/nbadiscussion",
    name: "r/NBAdiscussion",
    type: "reddit",
    url: "https://reddit.com/r/NBAdiscussion",
    config: JSON.stringify({"subreddit":"NBAdiscussion"}),
    isDefault: 0,
    vetted: 1,
    description: "Serious NBA analysis and discussion (no memes)",
    category: "sports",
  },
  {
    slug: "reddit/r/nfl",
    name: "r/nfl",
    type: "reddit",
    url: "https://reddit.com/r/nfl",
    config: JSON.stringify({"subreddit":"nfl"}),
    isDefault: 1,
    vetted: 1,
    description: "NFL news, highlights, and game threads",
    category: "sports",
  },
  {
    slug: "reddit/r/tennis",
    name: "r/tennis",
    type: "reddit",
    url: "https://reddit.com/r/tennis",
    config: JSON.stringify({"subreddit":"tennis"}),
    isDefault: 0,
    vetted: 1,
    description: "Professional tennis discussion and match threads",
    category: "sports",
  },
  {
    slug: "youtube/secret-base",
    name: "Secret Base",
    type: "youtube",
    url: "https://www.youtube.com/@SecretBase",
    config: JSON.stringify({"channelId":"UCDRmGMSgrtZkOsK_Pdy5yVA"}),
    isDefault: 1,
    vetted: 1,
    description: "Long-form sports documentaries and historical deep dives",
    category: "sports",
  },
  {
    slug: "bluesky/shams-charania",
    name: "Shams Charania",
    type: "bluesky",
    url: "https://bsky.app/profile/shamscharaniaespn.bsky.social",
    config: JSON.stringify({"actor":"shamscharaniaespn.bsky.social"}),
    isDefault: 1,
    vetted: 1,
    description: "NBA insider — breaking trades, free agency, and signings",
    category: "sports",
  },
  {
    slug: "rss/sports-illustrated",
    name: "Sports Illustrated",
    type: "rss",
    url: "https://www.si.com/feed",
    config: JSON.stringify({"feedUrl":"https://www.si.com/feed"}),
    isDefault: 0,
    vetted: 1,
    description: "Sports Illustrated features and analysis",
    category: "sports",
  },
  {
    slug: "bluesky/the-athletic",
    name: "The Athletic",
    type: "bluesky",
    url: "https://bsky.app/profile/theathletic.com",
    config: JSON.stringify({"actor":"theathletic.com"}),
    isDefault: 1,
    vetted: 1,
    description: "The Athletic's in-depth sports reporting",
    category: "sports",
  },
  {
    slug: "rss/guardian-football",
    name: "The Guardian Football",
    type: "rss",
    url: "https://www.theguardian.com/football/rss",
    config: JSON.stringify({"feedUrl":"https://www.theguardian.com/football/rss"}),
    isDefault: 0,
    vetted: 0,
    description: "The Guardian's football/soccer journalism",
    category: "sports",
  },
  {
    slug: "rss/the-race",
    name: "The Race",
    type: "rss",
    url: "https://the-race.com/feed/",
    config: JSON.stringify({"feedUrl":"https://the-race.com/feed/"}),
    isDefault: 0,
    vetted: 1,
    description: "Motorsport analysis from experienced journalists",
    category: "sports",
  },
  {
    slug: "youtube/thinking-basketball",
    name: "Thinking Basketball",
    type: "youtube",
    url: "https://www.youtube.com/@ThinkingBasketball",
    config: JSON.stringify({"channelId":"UCmSsHSJLVf1LVaGlSviZ9zg"}),
    isDefault: 1,
    vetted: 1,
    description: "NBA film study and analytical player evaluations",
    category: "sports",
  },
  {
    slug: "youtube/tifo-football",
    name: "Tifo Football",
    type: "youtube",
    url: "https://www.youtube.com/@TifoFootball",
    config: JSON.stringify({"channelId":"UCGYYNGmyhZ7ekQC4MIKrHAA"}),
    isDefault: 1,
    vetted: 1,
    description: "Tactical soccer analysis and animated explainers",
    category: "sports",
  },
  {
    slug: "bluesky/tom-bogert",
    name: "Tom Bogert",
    type: "bluesky",
    url: "https://bsky.app/profile/tombogert.bsky.social",
    config: JSON.stringify({"actor":"tombogert.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "MLS and American soccer insider",
    category: "sports",
  },
  {
    slug: "rss/yahoo-sports",
    name: "Yahoo Sports",
    type: "rss",
    url: "https://sports.yahoo.com/rss/",
    config: JSON.stringify({"feedUrl":"https://sports.yahoo.com/rss/"}),
    isDefault: 0,
    vetted: 1,
    description: "Yahoo Sports general headlines",
    category: "sports",
  },
  // ── Entertainment ────────────────────────────────────────────
  {
    slug: "rss/variety",
    name: "Variety",
    type: "rss",
    url: "https://variety.com/feed/",
    config: JSON.stringify({ feedUrl: "https://variety.com/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Film, TV, and entertainment industry news",
    category: "entertainment",
  },
  {
    slug: "rss/hollywood-reporter",
    name: "The Hollywood Reporter",
    type: "rss",
    url: "https://www.hollywoodreporter.com/feed/",
    config: JSON.stringify({ feedUrl: "https://www.hollywoodreporter.com/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Entertainment business and celebrity news",
    category: "entertainment",
  },
  {
    slug: "reddit/r/movies",
    name: "r/movies",
    type: "reddit",
    url: "https://reddit.com/r/movies",
    config: JSON.stringify({ subreddit: "movies" }),
    isDefault: 1,
    vetted: 1,
    description: "Movie news, reviews, and discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/entertainment",
    name: "r/entertainment",
    type: "reddit",
    url: "https://reddit.com/r/entertainment",
    config: JSON.stringify({ subreddit: "entertainment" }),
    isDefault: 0,
    vetted: 1,
    description: "Entertainment news across media",
    category: "entertainment",
  },
  {
    slug: "rss/slashfilm",
    name: "/Film",
    type: "rss",
    url: "https://www.slashfilm.com/feed/",
    config: JSON.stringify({"feedUrl":"https://www.slashfilm.com/feed/"}),
    isDefault: 1,
    vetted: 1,
    description: "Movie and TV news, trailers, interviews, and reviews",
    category: "entertainment",
  },
  {
    slug: "bluesky/sepinwall",
    name: "Alan Sepinwall",
    type: "bluesky",
    url: "https://bsky.app/profile/sepinwall.bsky.social",
    config: JSON.stringify({"actor":"sepinwall.bsky.social"}),
    isDefault: 1,
    vetted: 1,
    description: "Influential TV critic and author of The Revolution Was Televised",
    category: "entertainment",
  },
  {
    slug: "youtube/chris-stuckmann",
    name: "Chris Stuckmann",
    type: "youtube",
    url: "https://www.youtube.com/@ChrisStuckmann",
    config: JSON.stringify({"channelId":"UCTD8DtdOyVQ8XqADuixvH_g"}),
    isDefault: 1,
    vetted: 1,
    description: "Film criticism and reviews from one of YouTube's top movie critics",
    category: "entertainment",
  },
  {
    slug: "rss/collider",
    name: "Collider",
    type: "rss",
    url: "https://collider.com/feed/",
    config: JSON.stringify({"feedUrl":"https://collider.com/feed/"}),
    isDefault: 0,
    vetted: 1,
    description: "Movie and TV news, reviews, and streaming recommendations",
    category: "entertainment",
  },
  {
    slug: "rss/consequence",
    name: "Consequence of Sound",
    type: "rss",
    url: "https://consequence.net/feed/",
    config: JSON.stringify({"feedUrl":"https://consequence.net/feed/"}),
    isDefault: 0,
    vetted: 1,
    description: "Music, film, and TV news with concert/festival coverage",
    category: "entertainment",
  },
  {
    slug: "youtube/cosmonaut-variety-hour",
    name: "Cosmonaut Variety Hour",
    type: "youtube",
    url: "https://www.youtube.com/@CosmonautVarietyHour",
    config: JSON.stringify({"channelId":"UCqTYHSnBUXZamsVcOlQf-fg"}),
    isDefault: 0,
    vetted: 1,
    description: "Comedic film and TV retrospectives and media criticism",
    category: "entertainment",
  },
  {
    slug: "bluesky/david-ehrlich",
    name: "David Ehrlich",
    type: "bluesky",
    url: "https://bsky.app/profile/davidehrlich.bsky.social",
    config: JSON.stringify({"actor":"davidehrlich.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "IndieWire film critic known for annual best-of video countdowns",
    category: "entertainment",
  },
  {
    slug: "rss/deadline",
    name: "Deadline",
    type: "rss",
    url: "https://deadline.com/feed/",
    config: JSON.stringify({"feedUrl":"https://deadline.com/feed/"}),
    isDefault: 1,
    vetted: 1,
    description: "Breaking entertainment news — deals, casting, and box office",
    category: "entertainment",
  },
  {
    slug: "rss/e-online",
    name: "E! News",
    type: "rss",
    url: "https://www.eonline.com/feed",
    config: JSON.stringify({"feedUrl":"https://eol-feeds.eonline.com/rssfeed/us/top_stories"}),
    isDefault: 0,
    vetted: 1,
    description: "Celebrity news, red carpet, and pop culture",
    category: "entertainment",
  },
  {
    slug: "bluesky/ew",
    name: "Entertainment Weekly",
    type: "bluesky",
    url: "https://bsky.app/profile/ew.com",
    config: JSON.stringify({"actor":"ew.com"}),
    isDefault: 0,
    vetted: 1,
    description: "Pop culture news and entertainment coverage",
    category: "entertainment",
  },
  {
    slug: "rss/ign",
    name: "IGN",
    type: "rss",
    url: "https://feeds.feedburner.com/ign/all",
    config: JSON.stringify({"feedUrl":"https://feeds.feedburner.com/ign/all"}),
    isDefault: 1,
    vetted: 1,
    description: "Gaming and entertainment — news, reviews, and guides",
    category: "entertainment",
  },
  {
    slug: "rss/indiewire",
    name: "IndieWire",
    type: "rss",
    url: "https://www.indiewire.com/feed/",
    config: JSON.stringify({"feedUrl":"https://www.indiewire.com/feed/"}),
    isDefault: 1,
    vetted: 1,
    description: "Independent film, festival coverage, and awards analysis",
    category: "entertainment",
  },
  {
    slug: "bluesky/indiewire",
    name: "IndieWire",
    type: "bluesky",
    url: "https://bsky.app/profile/indiewire.com",
    config: JSON.stringify({"actor":"indiewire.com"}),
    isDefault: 1,
    vetted: 1,
    description: "Independent film news, reviews, and awards analysis",
    category: "entertainment",
  },
  {
    slug: "youtube/jeremy-jahns",
    name: "Jeremy Jahns",
    type: "youtube",
    url: "https://www.youtube.com/@JeremyJahns",
    config: JSON.stringify({"channelId":"UCk40qSGYnVdFFBNXRjrvdpQ"}),
    isDefault: 0,
    vetted: 1,
    description: "Quick-take movie and TV reviews with high-energy presentation",
    category: "entertainment",
  },
  {
    slug: "bluesky/justin-chang",
    name: "Justin Chang",
    type: "bluesky",
    url: "https://bsky.app/profile/justincchang.bsky.social",
    config: JSON.stringify({"actor":"justincchang.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "Film critic for The New Yorker and NPR — 2024 Pulitzer for Criticism",
    category: "entertainment",
  },
  {
    slug: "rss/kotaku",
    name: "Kotaku",
    type: "rss",
    url: "https://kotaku.com/rss",
    config: JSON.stringify({"feedUrl":"https://kotaku.com/rss"}),
    isDefault: 0,
    vetted: 1,
    description: "Gaming news with cultural commentary and industry reporting",
    category: "entertainment",
  },
  {
    slug: "bluesky/mark-harris",
    name: "Mark Harris",
    type: "bluesky",
    url: "https://bsky.app/profile/markharris.bsky.social",
    config: JSON.stringify({"actor":"markharris.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "Author and film historian — Pictures at a Revolution, Mike Nichols",
    category: "entertainment",
  },
  {
    slug: "bluesky/matt-zoller-seitz",
    name: "Matt Zoller Seitz",
    type: "bluesky",
    url: "https://bsky.app/profile/mattzollerseitz.bsky.social",
    config: JSON.stringify({"actor":"mattzollerseitz.bsky.social"}),
    isDefault: 0,
    vetted: 1,
    description: "Film critic, filmmaker, and RogerEbert.com editor-at-large",
    category: "entertainment",
  },
  {
    slug: "youtube/nerdwriter1",
    name: "Nerdwriter1",
    type: "youtube",
    url: "https://www.youtube.com/@Nerdwriter1",
    config: JSON.stringify({"channelId":"UCJkMlOu7faDgqh4PfzbpLdg"}),
    isDefault: 1,
    vetted: 1,
    description: "Video essays on film, art, philosophy, and cultural analysis",
    category: "entertainment",
  },
  {
    slug: "youtube/new-rockstars",
    name: "New Rockstars",
    type: "youtube",
    url: "https://www.youtube.com/@NewRockstars",
    config: JSON.stringify({"channelId":"UC7yRILFFJ2QZCykymr8LPwA"}),
    isDefault: 1,
    vetted: 1,
    description: "Film and TV breakdowns, trailer analysis, and easter egg deep dives",
    category: "entertainment",
  },
  {
    slug: "rss/nme",
    name: "NME",
    type: "rss",
    url: "https://www.nme.com/feed",
    config: JSON.stringify({"feedUrl":"https://www.nme.com/feed"}),
    isDefault: 0,
    vetted: 1,
    description: "UK-based music and entertainment news, reviews, and features",
    category: "entertainment",
  },
  {
    slug: "youtube/patrick-h-willems",
    name: "Patrick (H) Willems",
    type: "youtube",
    url: "https://www.youtube.com/@PatrickHWillems",
    config: JSON.stringify({"channelId":"UCMAwBUlaxyqZY-2hVac8qgg"}),
    isDefault: 0,
    vetted: 1,
    description: "Film video essays with creative framing and narrative experiments",
    category: "entertainment",
  },
  {
    slug: "rss/polygon",
    name: "Polygon",
    type: "rss",
    url: "https://www.polygon.com/rss/index.xml",
    config: JSON.stringify({"feedUrl":"https://www.polygon.com/rss/index.xml"}),
    isDefault: 0,
    vetted: 0,
    description: "Gaming and entertainment from a cultural perspective",
    category: "entertainment",
  },
  {
    slug: "bluesky/polygon",
    name: "Polygon",
    type: "bluesky",
    url: "https://bsky.app/profile/polygon.com",
    config: JSON.stringify({"actor":"polygon.com"}),
    isDefault: 0,
    vetted: 1,
    description: "Gaming and entertainment from a cultural perspective",
    category: "entertainment",
  },
  {
    slug: "reddit/r/boxoffice",
    name: "r/boxoffice",
    type: "reddit",
    url: "https://reddit.com/r/boxoffice",
    config: JSON.stringify({"subreddit":"boxoffice"}),
    isDefault: 0,
    vetted: 1,
    description: "Box office tracking, predictions, and industry analysis",
    category: "entertainment",
  },
  {
    slug: "reddit/r/games",
    name: "r/Games",
    type: "reddit",
    url: "https://reddit.com/r/Games",
    config: JSON.stringify({"subreddit":"Games"}),
    isDefault: 0,
    vetted: 1,
    description: "Serious gaming news and industry discussion (no memes)",
    category: "entertainment",
  },
  {
    slug: "reddit/r/gaming",
    name: "r/gaming",
    type: "reddit",
    url: "https://reddit.com/r/gaming",
    config: JSON.stringify({"subreddit":"gaming"}),
    isDefault: 1,
    vetted: 1,
    description: "Gaming news, memes, and community discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/hiphopheads",
    name: "r/hiphopheads",
    type: "reddit",
    url: "https://reddit.com/r/hiphopheads",
    config: JSON.stringify({"subreddit":"hiphopheads"}),
    isDefault: 0,
    vetted: 1,
    description: "Hip-hop news, new releases, and discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/indieheads",
    name: "r/indieheads",
    type: "reddit",
    url: "https://reddit.com/r/indieheads",
    config: JSON.stringify({"subreddit":"indieheads"}),
    isDefault: 0,
    vetted: 1,
    description: "Indie music news, reviews, and album discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/kpop",
    name: "r/kpop",
    type: "reddit",
    url: "https://reddit.com/r/kpop",
    config: JSON.stringify({"subreddit":"kpop"}),
    isDefault: 0,
    vetted: 1,
    description: "K-pop news, releases, and community",
    category: "entertainment",
  },
  {
    slug: "reddit/r/marvelstudios",
    name: "r/marvelstudios",
    type: "reddit",
    url: "https://reddit.com/r/marvelstudios",
    config: JSON.stringify({"subreddit":"marvelstudios"}),
    isDefault: 0,
    vetted: 1,
    description: "MCU news, theories, and discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/music",
    name: "r/music",
    type: "reddit",
    url: "https://reddit.com/r/music",
    config: JSON.stringify({"subreddit":"music"}),
    isDefault: 1,
    vetted: 1,
    description: "Music news, new releases, and community discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/oscars",
    name: "r/Oscars",
    type: "reddit",
    url: "https://reddit.com/r/Oscars",
    config: JSON.stringify({"subreddit":"Oscars"}),
    isDefault: 0,
    vetted: 1,
    description: "Oscar predictions, discussion, and awards season coverage",
    category: "entertainment",
  },
  {
    slug: "reddit/r/popculture",
    name: "r/popculture",
    type: "reddit",
    url: "https://reddit.com/r/popculture",
    config: JSON.stringify({"subreddit":"popculture"}),
    isDefault: 0,
    vetted: 1,
    description: "Pop culture news and celebrity discussion",
    category: "entertainment",
  },
  {
    slug: "reddit/r/television",
    name: "r/television",
    type: "reddit",
    url: "https://reddit.com/r/television",
    config: JSON.stringify({"subreddit":"television"}),
    isDefault: 1,
    vetted: 1,
    description: "TV show news, discussion, and recommendations",
    category: "entertainment",
  },
  {
    slug: "rss/roger-ebert",
    name: "Roger Ebert",
    type: "rss",
    url: "https://www.rogerebert.com/feed",
    config: JSON.stringify({"feedUrl":"https://www.rogerebert.com/feed"}),
    isDefault: 0,
    vetted: 1,
    description: "Film criticism and reviews — the gold standard in movie reviewing",
    category: "entertainment",
  },
  {
    slug: "rss/rolling-stone",
    name: "Rolling Stone",
    type: "rss",
    url: "https://www.rollingstone.com/feed/",
    config: JSON.stringify({"feedUrl":"https://www.rollingstone.com/feed/"}),
    isDefault: 1,
    vetted: 1,
    description: "Iconic music and culture magazine — news, reviews, features",
    category: "entertainment",
  },
  {
    slug: "bluesky/rolling-stone",
    name: "Rolling Stone",
    type: "bluesky",
    url: "https://bsky.app/profile/rollingstone.com",
    config: JSON.stringify({"actor":"rollingstone.com"}),
    isDefault: 1,
    vetted: 1,
    description: "Music and culture coverage from the iconic magazine",
    category: "entertainment",
  },
  {
    slug: "rss/screen-rant",
    name: "Screen Rant",
    type: "rss",
    url: "https://screenrant.com/feed/",
    config: JSON.stringify({"feedUrl":"https://screenrant.com/feed/"}),
    isDefault: 0,
    vetted: 1,
    description: "Movie/TV news, theories, and explainers (high volume)",
    category: "entertainment",
  },
  {
    slug: "youtube/screenjunkies",
    name: "ScreenJunkies",
    type: "youtube",
    url: "https://www.youtube.com/@ScreenJunkies",
    config: JSON.stringify({"channelId":"UCQMbqH7xJu5aTAPQ9y_U7WQ"}),
    isDefault: 1,
    vetted: 1,
    description: "Honest Trailers, movie debates, and entertainment commentary",
    category: "entertainment",
  },
  {
    slug: "youtube/skillup",
    name: "SkillUp",
    type: "youtube",
    url: "https://www.youtube.com/@SkillUp",
    config: JSON.stringify({"channelId":"UCZ7AeeVbyslLM_8-nVy2B8Q"}),
    isDefault: 0,
    vetted: 1,
    description: "In-depth game reviews and weekly gaming news roundups",
    category: "entertainment",
  },
  {
    slug: "rss/stereogum",
    name: "Stereogum",
    type: "rss",
    url: "https://www.stereogum.com/feed/",
    config: JSON.stringify({"feedUrl":"https://www.stereogum.com/feed/"}),
    isDefault: 0,
    vetted: 1,
    description: "Indie/alternative music blog — reviews, premieres, and features",
    category: "entertainment",
  },
  {
    slug: "rss/avclub",
    name: "The A.V. Club",
    type: "rss",
    url: "https://www.avclub.com/rss",
    config: JSON.stringify({"feedUrl":"https://www.avclub.com/rss"}),
    isDefault: 1,
    vetted: 1,
    description: "Pop culture criticism — TV recaps, movie reviews, music coverage",
    category: "entertainment",
  },
  {
    slug: "youtube/theneedledrop",
    name: "theneedledrop",
    type: "youtube",
    url: "https://www.youtube.com/@theneedledrop",
    config: JSON.stringify({"channelId":"UCnxQ8o9RpqxGF2oLHcCn9VQ"}),
    isDefault: 1,
    vetted: 1,
    description: "Anthony Fantano's album reviews — the internet's busiest music nerd",
    category: "entertainment",
  },
  {
    slug: "youtube/thomas-flight",
    name: "Thomas Flight",
    type: "youtube",
    url: "https://www.youtube.com/@ThomasFlight",
    config: JSON.stringify({"channelId":"UC-hehDTvO4X8d9M7MVtpElg"}),
    isDefault: 0,
    vetted: 1,
    description: "Video essays on filmmaking technique, editing, and storytelling",
    category: "entertainment",
  },
  {
    slug: "youtube/todd-in-the-shadows",
    name: "Todd in the Shadows",
    type: "youtube",
    url: "https://www.youtube.com/@ToddintheShadow",
    config: JSON.stringify({"channelId":"UCaTSjmqzOO-P8HmtVW3t7sA"}),
    isDefault: 0,
    vetted: 1,
    description: "Pop song reviews, one-hit wonders, and albums that killed careers",
    category: "entertainment",
  },
  {
    slug: "rss/tvline",
    name: "TVLine",
    type: "rss",
    url: "https://tvline.com/feed/",
    config: JSON.stringify({"feedUrl":"https://tvline.com/feed/"}),
    isDefault: 1,
    vetted: 1,
    description: "TV-focused news — spoilers, recaps, casting, renewals/cancellations",
    category: "entertainment",
  },
  {
    slug: "bluesky/variety",
    name: "Variety",
    type: "bluesky",
    url: "https://bsky.app/profile/variety.com",
    config: JSON.stringify({"actor":"variety.com"}),
    isDefault: 1,
    vetted: 1,
    description: "The business of entertainment — breaking industry news",
    category: "entertainment",
  },
  {
    slug: "youtube/videogamedunkey",
    name: "videogamedunkey",
    type: "youtube",
    url: "https://www.youtube.com/@videogamedunkey",
    config: JSON.stringify({"channelId":"UCsvn_Po0SmunchJYOWpOxMg"}),
    isDefault: 1,
    vetted: 1,
    description: "Gaming comedy, satire, and reviews blending humor with criticism",
    category: "entertainment",
  },
  {
    slug: "rss/vulture",
    name: "Vulture",
    type: "rss",
    url: "https://www.vulture.com/feed/rss/index.xml",
    config: JSON.stringify({"feedUrl":"https://www.vulture.com/feed/rss/index.xml"}),
    isDefault: 1,
    vetted: 1,
    description: "New York Magazine's entertainment vertical — deep cultural criticism",
    category: "entertainment",
  },
  {
    slug: "bluesky/vulture",
    name: "Vulture",
    type: "bluesky",
    url: "https://bsky.app/profile/vulture.com",
    config: JSON.stringify({"actor":"vulture.com"}),
    isDefault: 1,
    vetted: 1,
    description: "Deep cultural criticism and entertainment commentary",
    category: "entertainment",
  },
  {
    slug: "rss/whats-on-netflix",
    name: "What's on Netflix",
    type: "rss",
    url: "https://www.whats-on-netflix.com/feed/",
    config: JSON.stringify({"feedUrl":"https://www.whats-on-netflix.com/feed/"}),
    isDefault: 0,
    vetted: 1,
    description: "Netflix releases, leaving titles, and streaming news",
    category: "entertainment",
  },
];

export function seed() {
  for (const category of defaultCategories) {
    db.insert(categories).values(category).onConflictDoNothing().run();
  }

  for (const [slug, fields] of new Map(defaultCategories.map((c) => [c.slug, c]))) {
    db.update(categories)
      .set({ name: fields.name, ingestCron: fields.ingestCron, curateCron: fields.curateCron })
      .where(eq(categories.slug, slug))
      .run();
  }

  for (const source of defaultSources) {
    db.insert(sources).values(source).onConflictDoNothing().run();
  }

  const existingUser = db.select().from(users).limit(1).all();
  if (existingUser.length === 0) {
    db.insert(users)
      .values({ email: "user@local.dev", name: "Local User", onboarded: 1 })
      .run();
    db.insert(userPreferences)
      .values({
        userId: 1,
        topics: JSON.stringify([
          "typescript",
          "ai",
          "web development",
          "cloud computing",
          "devops",
          "security",
        ]),
        contentTypes: JSON.stringify([
          "article",
          "video",
          "short",
          "social",
        ]),
        digestSize: 50,
      })
      .run();
  }

  // Sync isDefault flags for existing sources (onConflictDoNothing won't update them)
  const defaultBySlug = new Map(defaultSources.map((s) => [s.slug, s.isDefault]));
  for (const [slug, isDefault] of defaultBySlug) {
    db.update(sources)
      .set({ isDefault })
      .where(eq(sources.slug, slug))
      .run();
  }

  // Sync category for seeded sources that declare one (onConflictDoNothing won't update them)
  const categoryBySlug = new Map(
    defaultSources
      .filter((s): s is typeof s & { category: string } => "category" in s)
      .map((s) => [s.slug, s.category])
  );
  for (const [slug, category] of categoryBySlug) {
    db.update(sources)
      .set({ category })
      .where(eq(sources.slug, slug))
      .run();
  }

  // Ensure digestSize is current for existing users
  db.update(userPreferences)
    .set({ digestSize: 50 })
    .where(eq(userPreferences.userId, 1))
    .run();
}
