import { db } from "./index";
import { sources, users, userPreferences } from "./schema";
import { eq } from "drizzle-orm";

const defaultSources = [
  // ── Hacker News ──────────────────────────────────────────────
  {
    slug: "hackernews",
    name: "Hacker News",
    type: "hackernews",
    url: "https://news.ycombinator.com",
    config: "{}",
    isDefault: 1,
    vetted: 1,
    description: "Top stories from YCombinator's Hacker News",
  },

  // ── Reddit ───────────────────────────────────────────────────
  {
    slug: "reddit/r/programming",
    name: "r/programming",
    type: "reddit",
    url: "https://reddit.com/r/programming",
    config: JSON.stringify({ subreddit: "programming" }),
    isDefault: 1,
    vetted: 1,
    description: "Programming news and discussion",
  },
  {
    slug: "reddit/r/typescript",
    name: "r/typescript",
    type: "reddit",
    url: "https://reddit.com/r/typescript",
    config: JSON.stringify({ subreddit: "typescript" }),
    isDefault: 1,
    vetted: 1,
    description: "TypeScript community",
  },
  {
    slug: "reddit/r/webdev",
    name: "r/webdev",
    type: "reddit",
    url: "https://reddit.com/r/webdev",
    config: JSON.stringify({ subreddit: "webdev" }),
    isDefault: 1,
    vetted: 1,
    description: "Web development community",
  },
  {
    slug: "reddit/r/machinelearning",
    name: "r/MachineLearning",
    type: "reddit",
    url: "https://reddit.com/r/MachineLearning",
    config: JSON.stringify({ subreddit: "MachineLearning" }),
    isDefault: 1,
    vetted: 1,
    description: "Machine learning research and discussion",
  },
  {
    slug: "reddit/r/devops",
    name: "r/devops",
    type: "reddit",
    url: "https://reddit.com/r/devops",
    config: JSON.stringify({ subreddit: "devops" }),
    isDefault: 1,
    vetted: 1,
    description: "DevOps practices and tooling",
  },
  {
    slug: "reddit/r/kubernetes",
    name: "r/kubernetes",
    type: "reddit",
    url: "https://reddit.com/r/kubernetes",
    config: JSON.stringify({ subreddit: "kubernetes" }),
    isDefault: 1,
    vetted: 1,
    description: "Kubernetes community",
  },

  // ── RSS: Cloud Providers ─────────────────────────────────────
  {
    slug: "rss/aws-blog",
    name: "AWS Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/aws/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/aws/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Primary AWS blog — new services, features, announcements",
  },
  {
    slug: "rss/aws-whats-new",
    name: "AWS What's New",
    type: "rss",
    url: "https://aws.amazon.com/about-aws/whats-new/recent/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/about-aws/whats-new/recent/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Every AWS service update and new feature launch (high volume)",
  },
  {
    slug: "rss/aws-security",
    name: "AWS Security Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/security/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/security/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "AWS security best practices, compliance, and encryption",
  },
  {
    slug: "rss/aws-architecture",
    name: "AWS Architecture Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/architecture/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/architecture/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Reference architectures and Well-Architected guidance",
  },
  {
    slug: "rss/aws-containers",
    name: "AWS Containers Blog",
    type: "rss",
    url: "https://aws.amazon.com/blogs/containers/feed/",
    config: JSON.stringify({ feedUrl: "https://aws.amazon.com/blogs/containers/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "ECS, EKS, Fargate, and container ecosystem on AWS",
  },
  {
    slug: "rss/gcp-blog",
    name: "Google Cloud Blog",
    type: "rss",
    url: "https://cloudblog.withgoogle.com/rss/",
    config: JSON.stringify({ feedUrl: "https://cloudblog.withgoogle.com/rss/" }),
    isDefault: 1,
    vetted: 1,
    description: "Google Cloud product announcements and case studies",
  },
  {
    slug: "rss/azure-blog",
    name: "Azure Blog",
    type: "rss",
    url: "https://azure.microsoft.com/en-us/blog/feed/",
    config: JSON.stringify({ feedUrl: "https://azure.microsoft.com/en-us/blog/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Azure announcements, tutorials, and updates",
  },
  {
    slug: "rss/cloudflare",
    name: "Cloudflare Blog",
    type: "rss",
    url: "https://blog.cloudflare.com/rss/",
    config: JSON.stringify({ feedUrl: "https://blog.cloudflare.com/rss/" }),
    isDefault: 1,
    vetted: 1,
    description: "Product launches, engineering deep dives, internet security",
  },
  {
    slug: "rss/vercel",
    name: "Vercel Blog",
    type: "rss",
    url: "https://vercel.com/atom",
    config: JSON.stringify({ feedUrl: "https://vercel.com/atom" }),
    isDefault: 1,
    vetted: 1,
    description: "Next.js hosting, edge functions, frontend cloud",
  },
  {
    slug: "rss/hashicorp",
    name: "HashiCorp Blog",
    type: "rss",
    url: "https://www.hashicorp.com/blog/feed.xml",
    config: JSON.stringify({ feedUrl: "https://www.hashicorp.com/blog/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Terraform, Vault, Consul, Nomad, and infrastructure automation",
  },

  // ── RSS: Security ────────────────────────────────────────────
  {
    slug: "rss/krebs",
    name: "Krebs on Security",
    type: "rss",
    url: "https://krebsonsecurity.com/feed/",
    config: JSON.stringify({ feedUrl: "https://krebsonsecurity.com/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "Investigative journalism on cybercrime and security",
  },
  {
    slug: "rss/hacker-news-security",
    name: "The Hacker News",
    type: "rss",
    url: "https://feeds.feedburner.com/TheHackersNews",
    config: JSON.stringify({ feedUrl: "https://feeds.feedburner.com/TheHackersNews" }),
    isDefault: 1,
    vetted: 1,
    description: "Cybersecurity news — vulnerabilities, breaches, threats",
  },
  {
    slug: "rss/bleeping-computer",
    name: "BleepingComputer",
    type: "rss",
    url: "https://www.bleepingcomputer.com/feed/",
    config: JSON.stringify({ feedUrl: "https://www.bleepingcomputer.com/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Breaking security news and malware analysis",
  },
  {
    slug: "rss/schneier",
    name: "Schneier on Security",
    type: "rss",
    url: "https://www.schneier.com/feed/atom/",
    config: JSON.stringify({ feedUrl: "https://www.schneier.com/feed/atom/" }),
    isDefault: 0,
    vetted: 1,
    description: "Expert commentary on security, privacy, and cryptography",
  },
  {
    slug: "rss/project-zero",
    name: "Google Project Zero",
    type: "rss",
    url: "https://googleprojectzero.blogspot.com/feeds/posts/default",
    config: JSON.stringify({ feedUrl: "https://googleprojectzero.blogspot.com/feeds/posts/default" }),
    isDefault: 0,
    vetted: 1,
    description: "Vulnerability research and zero-day disclosure",
  },
  {
    slug: "rss/portswigger",
    name: "PortSwigger Research",
    type: "rss",
    url: "https://portswigger.net/research/rss",
    config: JSON.stringify({ feedUrl: "https://portswigger.net/research/rss" }),
    isDefault: 0,
    vetted: 1,
    description: "Web security research from the creators of Burp Suite",
  },

  // ── RSS: AI & Research ───────────────────────────────────────
  {
    slug: "rss/openai",
    name: "OpenAI Blog",
    type: "rss",
    url: "https://openai.com/blog/rss.xml",
    config: JSON.stringify({ feedUrl: "https://openai.com/blog/rss.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Model releases, research papers, and safety updates",
  },
  {
    slug: "rss/deepmind",
    name: "Google DeepMind",
    type: "rss",
    url: "https://deepmind.google/blog/rss.xml",
    config: JSON.stringify({ feedUrl: "https://deepmind.google/blog/rss.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "AI research breakthroughs and scientific applications",
  },
  {
    slug: "rss/huggingface",
    name: "Hugging Face Blog",
    type: "rss",
    url: "https://huggingface.co/blog/feed.xml",
    config: JSON.stringify({ feedUrl: "https://huggingface.co/blog/feed.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Open-source ML models, transformers, and community updates",
  },
  {
    slug: "rss/simon-willison",
    name: "Simon Willison's Blog",
    type: "rss",
    url: "https://simonwillison.net/atom/everything/",
    config: JSON.stringify({ feedUrl: "https://simonwillison.net/atom/everything/" }),
    isDefault: 1,
    vetted: 1,
    description: "Prolific coverage of LLMs, AI tools, Python, and open data",
  },
  {
    slug: "rss/lilian-weng",
    name: "Lilian Weng",
    type: "rss",
    url: "https://lilianweng.github.io/index.xml",
    config: JSON.stringify({ feedUrl: "https://lilianweng.github.io/index.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Exceptional long-form ML explainers from OpenAI researcher",
  },

  // ── RSS: General Tech News ───────────────────────────────────
  {
    slug: "rss/tldr",
    name: "TLDR Newsletter",
    type: "rss",
    url: "https://tldr.tech/api/rss/tech",
    config: JSON.stringify({ feedUrl: "https://tldr.tech/api/rss/tech" }),
    isDefault: 1,
    vetted: 1,
    description: "Daily tech newsletter digest",
  },
  {
    slug: "rss/ars-technica",
    name: "Ars Technica",
    type: "rss",
    url: "https://feeds.arstechnica.com/arstechnica/index",
    config: JSON.stringify({ feedUrl: "https://feeds.arstechnica.com/arstechnica/index" }),
    isDefault: 1,
    vetted: 1,
    description: "In-depth tech, science, and policy journalism",
  },
  {
    slug: "rss/the-verge",
    name: "The Verge",
    type: "rss",
    url: "https://www.theverge.com/rss/index.xml",
    config: JSON.stringify({ feedUrl: "https://www.theverge.com/rss/index.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Tech, science, culture, and industry news",
  },
  {
    slug: "rss/techcrunch",
    name: "TechCrunch",
    type: "rss",
    url: "https://techcrunch.com/feed/",
    config: JSON.stringify({ feedUrl: "https://techcrunch.com/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Startup ecosystem, funding rounds, and tech industry",
  },
  {
    slug: "rss/techmeme",
    name: "Techmeme",
    type: "rss",
    url: "https://www.techmeme.com/feed.xml",
    config: JSON.stringify({ feedUrl: "https://www.techmeme.com/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Curated aggregation of the most important tech news",
  },
  {
    slug: "rss/lobsters",
    name: "Lobsters",
    type: "rss",
    url: "https://lobste.rs/rss",
    config: JSON.stringify({ feedUrl: "https://lobste.rs/rss" }),
    isDefault: 1,
    vetted: 1,
    description: "Invite-only computing-focused link aggregation",
  },
  {
    slug: "rss/pragmatic-engineer",
    name: "The Pragmatic Engineer",
    type: "rss",
    url: "https://blog.pragmaticengineer.com/rss/",
    config: JSON.stringify({ feedUrl: "https://blog.pragmaticengineer.com/rss/" }),
    isDefault: 0,
    vetted: 1,
    description: "Engineering management and big tech insights",
  },
  {
    slug: "rss/netflix-tech",
    name: "Netflix Tech Blog",
    type: "rss",
    url: "https://medium.com/feed/netflix-techblog",
    config: JSON.stringify({ feedUrl: "https://medium.com/feed/netflix-techblog" }),
    isDefault: 0,
    vetted: 1,
    description: "Distributed systems, streaming infrastructure, and ML at scale",
  },

  // ── RSS: Developer Tools & Frameworks ────────────────────────
  {
    slug: "rss/react",
    name: "React Blog",
    type: "rss",
    url: "https://react.dev/rss.xml",
    config: JSON.stringify({ feedUrl: "https://react.dev/rss.xml" }),
    isDefault: 1,
    vetted: 1,
    description: "Official React team updates and releases",
  },
  {
    slug: "rss/typescript",
    name: "TypeScript Blog",
    type: "rss",
    url: "https://devblogs.microsoft.com/typescript/feed/",
    config: JSON.stringify({ feedUrl: "https://devblogs.microsoft.com/typescript/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "TypeScript releases and type system features",
  },
  {
    slug: "rss/tailwind",
    name: "Tailwind CSS Blog",
    type: "rss",
    url: "https://tailwindcss.com/feeds/feed.xml",
    config: JSON.stringify({ feedUrl: "https://tailwindcss.com/feeds/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Tailwind releases and utility-first CSS updates",
  },
  {
    slug: "rss/rust",
    name: "Rust Blog",
    type: "rss",
    url: "https://blog.rust-lang.org/feed.xml",
    config: JSON.stringify({ feedUrl: "https://blog.rust-lang.org/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Rust releases, edition updates, and RFCs",
  },
  {
    slug: "rss/go",
    name: "Go Blog",
    type: "rss",
    url: "https://go.dev/blog/feed.atom",
    config: JSON.stringify({ feedUrl: "https://go.dev/blog/feed.atom" }),
    isDefault: 0,
    vetted: 1,
    description: "Official Go blog — releases, proposals, patterns",
  },
  {
    slug: "rss/github-blog",
    name: "GitHub Blog",
    type: "rss",
    url: "https://github.blog/feed/",
    config: JSON.stringify({ feedUrl: "https://github.blog/feed/" }),
    isDefault: 1,
    vetted: 1,
    description: "GitHub features, Copilot updates, developer ecosystem",
  },
  {
    slug: "rss/github-changelog",
    name: "GitHub Changelog",
    type: "rss",
    url: "https://github.blog/changelog/feed/",
    config: JSON.stringify({ feedUrl: "https://github.blog/changelog/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Granular changelog of every GitHub feature and UI change",
  },
  {
    slug: "rss/kubernetes",
    name: "Kubernetes Blog",
    type: "rss",
    url: "https://kubernetes.io/feed.xml",
    config: JSON.stringify({ feedUrl: "https://kubernetes.io/feed.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "K8s releases, KEPs, and CNCF ecosystem updates",
  },
  {
    slug: "rss/docker",
    name: "Docker Blog",
    type: "rss",
    url: "https://www.docker.com/blog/feed/",
    config: JSON.stringify({ feedUrl: "https://www.docker.com/blog/feed/" }),
    isDefault: 0,
    vetted: 1,
    description: "Docker Desktop, Docker Hub, and container ecosystem",
  },
  {
    slug: "rss/grafana",
    name: "Grafana Blog",
    type: "rss",
    url: "https://grafana.com/blog/index.xml",
    config: JSON.stringify({ feedUrl: "https://grafana.com/blog/index.xml" }),
    isDefault: 0,
    vetted: 1,
    description: "Observability, dashboards, Loki, Tempo, and Mimir",
  },

  // ── YouTube ──────────────────────────────────────────────────
  {
    slug: "youtube/fireship",
    name: "Fireship",
    type: "youtube",
    url: "https://www.youtube.com/@Fireship",
    config: JSON.stringify({ channelId: "UCsBjURrPoezykLs9EqgamOA" }),
    isDefault: 0,
    vetted: 1,
    description: "Fast-paced tech tutorials and news",
  },
  {
    slug: "youtube/theo",
    name: "Theo - t3.gg",
    type: "youtube",
    url: "https://www.youtube.com/@t3dotgg",
    config: JSON.stringify({ channelId: "UCbRP3c757lWg9M-U7TyEkXA" }),
    isDefault: 0,
    vetted: 1,
    description: "TypeScript, Next.js, tRPC, and web dev opinions",
  },
  {
    slug: "youtube/3blue1brown",
    name: "3Blue1Brown",
    type: "youtube",
    url: "https://www.youtube.com/@3blue1brown",
    config: JSON.stringify({ channelId: "UCYO_jab_esuFRV4b17AJtAw" }),
    isDefault: 0,
    vetted: 1,
    description: "Mathematical foundations of ML/AI with visual explanations",
  },
  {
    slug: "youtube/andrej-karpathy",
    name: "Andrej Karpathy",
    type: "youtube",
    url: "https://www.youtube.com/@andrejkarpathy",
    config: JSON.stringify({ channelId: "UCXUPKJO5MZQN11PqgIvyuvQ" }),
    isDefault: 0,
    vetted: 1,
    description: "First-principles neural network and LLM tutorials",
  },
  {
    slug: "youtube/yannic-kilcher",
    name: "Yannic Kilcher",
    type: "youtube",
    url: "https://www.youtube.com/@YannicKilcher",
    config: JSON.stringify({ channelId: "UCZHmQk67mSJgfCCTn7xBfew" }),
    isDefault: 0,
    vetted: 1,
    description: "Rigorous ML research paper breakdowns",
  },
  {
    slug: "youtube/two-minute-papers",
    name: "Two Minute Papers",
    type: "youtube",
    url: "https://www.youtube.com/@TwoMinutePapers",
    config: JSON.stringify({ channelId: "UCbfYPyITQ-7l4upoX8nvctg" }),
    isDefault: 1,
    vetted: 1,
    description: "Concise summaries of cutting-edge AI research",
  },
  {
    slug: "youtube/ai-explained",
    name: "AI Explained",
    type: "youtube",
    url: "https://www.youtube.com/@aiexplained-official",
    config: JSON.stringify({ channelId: "UCNJ1Ymd5yFuUPtn21xtRbbw" }),
    isDefault: 1,
    vetted: 1,
    description: "Thorough, measured analysis of major AI developments",
  },
  {
    slug: "youtube/1littlecoder",
    name: "1littlecoder",
    type: "youtube",
    url: "https://www.youtube.com/@1littlecoder",
    config: JSON.stringify({ channelId: "UCpV_X0VrL8-jg3t6wYGS-1g" }),
    isDefault: 1,
    vetted: 1,
    description: "AI/ML coding tutorials and tool walkthroughs",
  },
  {
    slug: "youtube/dylan-curious",
    name: "Dylan Curious",
    type: "youtube",
    url: "https://www.youtube.com/@Dylan_Curious",
    config: JSON.stringify({ channelId: "UCpdyFxSktWo3W6kMYfmk6lg" }),
    isDefault: 1,
    vetted: 1,
    description: "AI and tech curiosity-driven explainers",
  },
  {
    slug: "youtube/arseny-shatokhin",
    name: "Arseny Shatokhin",
    type: "youtube",
    url: "https://www.youtube.com/@vrsen",
    config: JSON.stringify({ channelId: "UCSv4qL8vmoSH7GaPjuqRiCQ" }),
    isDefault: 1,
    vetted: 1,
    description: "AI engineering and agent development tutorials",
  },
  {
    slug: "youtube/matt-pocock",
    name: "Matt Pocock",
    type: "youtube",
    url: "https://www.youtube.com/@mattpocockuk",
    config: JSON.stringify({ channelId: "UCswG6FSbgZjbWtdf_hMLaow" }),
    isDefault: 0,
    vetted: 1,
    description: "Advanced TypeScript patterns and type-level programming",
  },
  {
    slug: "youtube/primeagen",
    name: "ThePrimeagen",
    type: "youtube",
    url: "https://www.youtube.com/@ThePrimeagen",
    config: JSON.stringify({ channelId: "UC8ENHE5xdFSwx71u3fDH5Xw" }),
    isDefault: 0,
    vetted: 1,
    description: "Backend performance, Rust, Go, algorithms, engineering culture",
  },
  {
    slug: "youtube/jack-herrington",
    name: "Jack Herrington",
    type: "youtube",
    url: "https://www.youtube.com/@jherr",
    config: JSON.stringify({ channelId: "UC6vRUjYqDuoUsYsku86Lrsw" }),
    isDefault: 0,
    vetted: 1,
    description: "Advanced React patterns and micro-frontends",
  },
  // ── Bluesky ──────────────────────────────────────────────────
  {
    slug: "bluesky/simon-willison",
    name: "Simon Willison",
    type: "bluesky",
    url: "https://bsky.app/profile/simonwillison.net",
    config: JSON.stringify({ actor: "simonwillison.net" }),
    isDefault: 1,
    vetted: 1,
    description: "AI tools, LLMs, Python, and open data",
  },
  {
    slug: "bluesky/swyx",
    name: "swyx",
    type: "bluesky",
    url: "https://bsky.app/profile/swyx.io",
    config: JSON.stringify({ actor: "swyx.io" }),
    isDefault: 1,
    vetted: 1,
    description: "Latent Space podcast, AI engineering",
  },
  {
    slug: "bluesky/andrej-karpathy",
    name: "Andrej Karpathy",
    type: "bluesky",
    url: "https://bsky.app/profile/karpathy.bsky.social",
    config: JSON.stringify({ actor: "karpathy.bsky.social" }),
    isDefault: 1,
    vetted: 1,
    description: "AI researcher, deep learning and LLMs",
  },
  {
    slug: "bluesky/kelsey-hightower",
    name: "Kelsey Hightower",
    type: "bluesky",
    url: "https://bsky.app/profile/kelseyhightower.com",
    config: JSON.stringify({ actor: "kelseyhightower.com" }),
    isDefault: 1,
    vetted: 1,
    description: "Cloud-native, Kubernetes, infrastructure",
  },
  {
    slug: "bluesky/julia-evans",
    name: "Julia Evans",
    type: "bluesky",
    url: "https://bsky.app/profile/b0rk.jvns.ca",
    config: JSON.stringify({ actor: "b0rk.jvns.ca" }),
    isDefault: 1,
    vetted: 1,
    description: "Wizard Zines — Linux, networking, debugging",
  },
  {
    slug: "bluesky/dan-abramov",
    name: "Dan Abramov",
    type: "bluesky",
    url: "https://bsky.app/profile/danabra.mov",
    config: JSON.stringify({ actor: "danabra.mov" }),
    isDefault: 1,
    vetted: 1,
    description: "Former React core team, Redux creator",
  },
  {
    slug: "bluesky/kent-c-dodds",
    name: "Kent C. Dodds",
    type: "bluesky",
    url: "https://bsky.app/profile/kentcdodds.com",
    config: JSON.stringify({ actor: "kentcdodds.com" }),
    isDefault: 0,
    vetted: 1,
    description: "EpicWeb.dev, React and testing expert",
  },
  {
    slug: "bluesky/charity-majors",
    name: "Charity Majors",
    type: "bluesky",
    url: "https://bsky.app/profile/charity.wtf",
    config: JSON.stringify({ actor: "charity.wtf" }),
    isDefault: 0,
    vetted: 1,
    description: "Honeycomb CTO, observability pioneer",
  },
  {
    slug: "bluesky/theo",
    name: "Theo",
    type: "bluesky",
    url: "https://bsky.app/profile/t3.gg",
    config: JSON.stringify({ actor: "t3.gg" }),
    isDefault: 0,
    vetted: 1,
    description: "T3 stack, TypeScript, Next.js",
  },
  {
    slug: "bluesky/rich-harris",
    name: "Rich Harris",
    type: "bluesky",
    url: "https://bsky.app/profile/rich-harris.dev",
    config: JSON.stringify({ actor: "rich-harris.dev" }),
    isDefault: 0,
    vetted: 1,
    description: "Creator of Svelte and SvelteKit",
  },
  {
    slug: "bluesky/matt-pocock",
    name: "Matt Pocock",
    type: "bluesky",
    url: "https://bsky.app/profile/mattpocock.com",
    config: JSON.stringify({ actor: "mattpocock.com" }),
    isDefault: 0,
    vetted: 1,
    description: "Total TypeScript, TS educator",
  },
  {
    slug: "bluesky/corey-quinn",
    name: "Corey Quinn",
    type: "bluesky",
    url: "https://bsky.app/profile/quinnypig.com",
    config: JSON.stringify({ actor: "quinnypig.com" }),
    isDefault: 0,
    vetted: 1,
    description: "Last Week in AWS, cloud economics",
  },
  {
    slug: "bluesky/liz-rice",
    name: "Liz Rice",
    type: "bluesky",
    url: "https://bsky.app/profile/lizrice.com",
    config: JSON.stringify({ actor: "lizrice.com" }),
    isDefault: 0,
    vetted: 1,
    description: "eBPF/Cilium expert, container security author",
  },
  {
    slug: "bluesky/wes-bos",
    name: "Wes Bos",
    type: "bluesky",
    url: "https://bsky.app/profile/wesbos.com",
    config: JSON.stringify({ actor: "wesbos.com" }),
    isDefault: 0,
    vetted: 1,
    description: "Syntax podcast, JS/CSS/Node courses",
  },
];

export function seed() {
  for (const source of defaultSources) {
    db.insert(sources).values(source).onConflictDoNothing().run();
  }

  const existingUser = db.select().from(users).limit(1).all();
  if (existingUser.length === 0) {
    db.insert(users)
      .values({ email: "user@local.dev", name: "Local User", onboarded: 1 })
      .run();
    db.insert(userPreferences)
      .values({
        userId: 1,
        topics: JSON.stringify([
          "typescript",
          "ai",
          "web development",
          "cloud computing",
          "devops",
          "security",
        ]),
        contentTypes: JSON.stringify([
          "article",
          "video",
          "short",
          "social",
        ]),
        digestSize: 50,
      })
      .run();
  }

  // Sync isDefault flags for existing sources (onConflictDoNothing won't update them)
  const defaultBySlug = new Map(defaultSources.map((s) => [s.slug, s.isDefault]));
  for (const [slug, isDefault] of defaultBySlug) {
    db.update(sources)
      .set({ isDefault })
      .where(eq(sources.slug, slug))
      .run();
  }

  // Ensure digestSize is current for existing users
  db.update(userPreferences)
    .set({ digestSize: 50 })
    .where(eq(userPreferences.userId, 1))
    .run();
}
